### ISSUE TITLE
Bug: Error when trying to install tooth using ``LL``

### ISSUE THREAD

**Issue by harry-xi** [LiteLDev/Lip#88]
> 我不确定这个问题是属于注册库还是属于lip本体

## BUG描述
尝试通过ll别名安装liteloaderbds引发lip报错，不排除问题是注册库内文件有误（我没有去检查是否可能为该情况）
通过名称liteloaderbds安装ll不会引发该报错，未测试其他包的情况

## 如何复现
重现该行为的步骤：

输入`lip i ll`或`lip show ll`

## 日志输出
![image](https://user-images.githubusercontent.com/79187160/230626526-3a44d904-5195-4626-bf82-bd6ab12cd5bd.png)

```text
❯ lip i ll@2.12.3
Validating specifiers...
  Validating ll@2.12.3...
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/liteldev/lip/registry.LookupAlias({0xc00001c0d0, 0x2})
        /home/runner/work/Lip/Lip/src/registry/utils.go:55 +0x8b7
github.com/liteldev/lip/specifiers.New({0xc00001c0d0, 0x9})
        /home/runner/work/Lip/Lip/src/specifiers/specifier.go:85 +0x2eb
github.com/liteldev/lip/cmd/install.Run({0xc00006c060, 0x1, 0x2})
        /home/runner/work/Lip/Lip/src/cmd/install/install.go:94 +0x36c8
github.com/liteldev/lip/cmd.Run({0xc00006c050, 0x2, 0x3})
        /home/runner/work/Lip/Lip/src/cmd/lip.go:120 +0x65c
main.main()
        /home/runner/work/Lip/Lip/src/main.go:95 +0x50d

❯ lip -V
Lip 0.14.0 from D:\Docu.Haiyue\Minecraft\Tools\Lip\lip.exe
```

## 平台

- OS: Windows 10 22H2
- Lip version:  0.14.0

**Comment by Futrime** [comment]
@harry-xi registry的问题，registry更新了但lip还没更新（悲

**Comment by RimuruChan** [comment]
@harry-xi 建议先改回去，我重构还要点时间

**Comment by RimuruChan** [comment]
fix in https://github.com/LiteLDev/Registry/commit/2ff466cd4ea1ef0e5baa0eb6a3d640079a464f61
